#include "systemctrl.h"
#include "systemctrl_se.h"
#include "utils.h"
#include "main.h"

const char * g_messages_cht[] = {
	"PRO 恢復菜單",
	"主菜單",
	"進入中",
	"退出中",
	"返回",
	"默認",
	"啟用",
	"禁用",
	"切換USB",
	"啟用USB",
	"禁用USB",
	"基本設置",
	"區域欺騙",
	"恢復菜單字體",
	"ISO 模式",
	"標準",
	"M33 driver",
	"Sony NP9660",
	"Inferno",
	"USB 設備",
	"Flash 0",
	"Flash 1",
	"Flash 2",
	"Flash 3",
	"UMD Disc",
	"連接 USB時給電池充電 (PSP-1000無效)",
	"使用Slim顏色 (PSP-1000專用)",
	"使用htmlviewer自定義保存位置",
	"隱藏 MAC地址",
	"啟動時跳過Sony Logo",
	"跳過游戲啟動畫面",
	"游戲列表中隱藏PIC0.PNG和PIC1.PNG",
	"保護 USB設備安裝Flash",
	"使用/seplugins/version.txt",
	"使用/seplugins/usbversion.txt",
	"使用自定義更新服務器",
	"阻止刪除休眠文件 (PSP-Go專用)",
	"高級設置",
	"插件(XMB)",
	"插件(Game)",
	"插件(Pops)",
	"NoDRM 引擎",
	"游戲時隱藏 CFW文件",
	"游戲時禁用搖桿",
	"舊插件支持(PSP-Go專用)",
	"Inferno & NP9660 使用ISO高速緩存",
	"Inferno & NP9660 緩存大小(MB)",
	"Inferno & NP9660 緩存數",
	"Inferno & NP9660 緩存策略",
	"允許非latin1的ISO文件名",
	"Memory Stick加速",
	"無",
	"Pop",
	"Game",
	"Vsh",
	"Pop & Game",
	"Game & Vsh",
	"Vsh & Pop",
	"始終",
	"CPU 頻率",
	"CPU/BUS(XMB) ",
	"CPU/BUS(Game)",
	"插件管理",
	"System Storage",
	"Memory Stick",
	"插件在System Storage",
	"插件在Memory Stick",
	"注冊表破解",
	"WMA 激活",
	"Flash 激活",
	"按鈕交換",
	"確認按鈕: X",
	"確認按鈕: O",
	"激活 WMA",
	"激活 Flash",
	"交換 O/X按鈕",
	"交換 O/X按鈕 (需重啟 VSH后才能生效)",
	"刪除休眠文件 (PSP-Go專用)",
	"休眠文件刪除",
	"運行/PSP/GAME/RECOVERY/EBOOT.PBP",
	"關閉設備",
	"掛起設備",
	"重啟設備",
	"重啟VSH",
	"分頁",
	"日本",
	"美國",
	"歐洲",
	"韓國",
	"英國",
	"墨西哥",
	"澳大利亞",
	"香港",
	"臺灣",
	"俄羅斯",
	"中國",
	"調試類型I",
	"調試類型II",
	"解鎖PSP游戲內存 (休眠主屏幕)",
};

u8 message_test_cht[NELEMS(g_messages_cht) == MSG_END ? 0 : -1];
